// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fileShowLines
int fileShowLines(Rcpp::CharacterVector rfileInput, Rcpp::NumericVector rnLimitLines = Rcpp::NumericVector::create(100));
RcppExport SEXP fwftools_fileShowLines(SEXP rfileInputSEXP, SEXP rnLimitLinesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type rfileInput(rfileInputSEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rnLimitLines(rnLimitLinesSEXP );
        int __result = fileShowLines(rfileInput, rnLimitLines);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
