// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cppTest
Rcpp::IntegerVector cppTest(Rcpp::IntegerVector begin, Rcpp::IntegerVector end);
RcppExport SEXP fwftools_cppTest(SEXP beginSEXP, SEXP endSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type begin(beginSEXP );
        Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type end(endSEXP );
        Rcpp::IntegerVector __result = cppTest(begin, end);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// fileCountLines
int fileCountLines(Rcpp::CharacterVector file);
RcppExport SEXP fwftools_fileCountLines(SEXP fileSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type file(fileSEXP );
        int __result = fileCountLines(file);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// fileFWFtoCSV
void fileFWFtoCSV(Rcpp::CharacterVector inputFile, Rcpp::CharacterVector outputFile, Rcpp::IntegerVector begin, Rcpp::IntegerVector end, Rcpp::CharacterVector header1 = Rcpp::CharacterVector::create("a"), Rcpp::CharacterVector header2 = Rcpp::CharacterVector::create("a"), long skip = 0, long limit = 0, Rcpp::CharacterVector mode = Rcpp::CharacterVector::create("a"));
RcppExport SEXP fwftools_fileFWFtoCSV(SEXP inputFileSEXP, SEXP outputFileSEXP, SEXP beginSEXP, SEXP endSEXP, SEXP header1SEXP, SEXP header2SEXP, SEXP skipSEXP, SEXP limitSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type inputFile(inputFileSEXP );
        Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type outputFile(outputFileSEXP );
        Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type begin(beginSEXP );
        Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type end(endSEXP );
        Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type header1(header1SEXP );
        Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type header2(header2SEXP );
        Rcpp::traits::input_parameter< long >::type skip(skipSEXP );
        Rcpp::traits::input_parameter< long >::type limit(limitSEXP );
        Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type mode(modeSEXP );
        fileFWFtoCSV(inputFile, outputFile, begin, end, header1, header2, skip, limit, mode);
    }
    return R_NilValue;
END_RCPP
}
// fileShowLines
void fileShowLines(Rcpp::CharacterVector file, long n = 100);
RcppExport SEXP fwftools_fileShowLines(SEXP fileSEXP, SEXP nSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type file(fileSEXP );
        Rcpp::traits::input_parameter< long >::type n(nSEXP );
        fileShowLines(file, n);
    }
    return R_NilValue;
END_RCPP
}
// fileShowMidLines
void fileShowMidLines(Rcpp::CharacterVector file, long begin = 1, long end = 100);
RcppExport SEXP fwftools_fileShowMidLines(SEXP fileSEXP, SEXP beginSEXP, SEXP endSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type file(fileSEXP );
        Rcpp::traits::input_parameter< long >::type begin(beginSEXP );
        Rcpp::traits::input_parameter< long >::type end(endSEXP );
        fileShowMidLines(file, begin, end);
    }
    return R_NilValue;
END_RCPP
}
