# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cppTest <- function(begin, end) {
    .Call('fwftools_cppTest', PACKAGE = 'fwftools', begin, end)
}

#' @export
fileCountLines <- function(file) {
    .Call('fwftools_fileCountLines', PACKAGE = 'fwftools', file)
}

#' @export
fileFWFtoCSV <- function(inputFile, outputFile, begin, end, header1 = as.character( c("")), header2 = as.character( c("")), skip = 0L, limit = 0L, mode = as.character( c("n"))) {
    invisible(.Call('fwftools_fileFWFtoCSV', PACKAGE = 'fwftools', inputFile, outputFile, begin, end, header1, header2, skip, limit, mode))
}

#' @export
fileFWFtoCSVtime <- function(inputFile, outputFile, begin, end, header1 = as.character( c("")), header2 = as.character( c("")), skip = 0L, limit = 1000L) {
    .Call('fwftools_fileFWFtoCSVtime', PACKAGE = 'fwftools', inputFile, outputFile, begin, end, header1, header2, skip, limit)
}

#' @export
fileShowLines <- function(file, n = 100L) {
    invisible(.Call('fwftools_fileShowLines', PACKAGE = 'fwftools', file, n))
}

#' @export
fileShowMidLines <- function(file, nini = 1L, nend = 100L) {
    invisible(.Call('fwftools_fileShowMidLines', PACKAGE = 'fwftools', file, nini, nend))
}

