# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
fileShowLines <- function(rfileInput, rnLimitLines = as.numeric( c(100))) {
    .Call('fwftools_fileShowLines', PACKAGE = 'fwftools', rfileInput, rnLimitLines)
}

