# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
fileCountLines <- function(file) {
    .Call('fwftools_fileCountLines', PACKAGE = 'fwftools', file)
}

#' @export
fileShowLines <- function(file, n = 100L) {
    invisible(.Call('fwftools_fileShowLines', PACKAGE = 'fwftools', file, n))
}

#' @export
fileShowMidLines <- function(file, begin = 1L, end = 100L) {
    invisible(.Call('fwftools_fileShowMidLines', PACKAGE = 'fwftools', file, begin, end))
}

